#!/bin/bash

# The wallpaper path is the first argument passed to the script
WALLPAPER="$1"

# Define the path to your Mako config file
MAKO_CONFIG="$HOME/.config/mako/config"
WAL_CACHE="$HOME/.cache/wal/colors.json"

# Check if the wallpaper exists
if [ ! -f "$WALLPAPER" ]; then
    echo "Error: Wallpaper not found at $WALLPAPER"
    exit 1
fi

# Use jq to extract hex color values from the colors.json file
BACKGROUND_COLOR=$(jq -r '.special.background' "$WAL_CACHE")
TEXT_COLOR=$(jq -r '.special.foreground' "$WAL_CACHE")
BORDER_COLOR=$(jq -r '.colors.color5' "$WAL_CACHE") # Using a highlight color

# Now, we rewrite the Mako config file with the new colors.
cat > "$MAKO_CONFIG" <<EOF
# Mako config regenerated by Pywal script

# Global colors
# Colors can be specified as #RRGGBB or #RRGGBBAA
background-color=$BACKGROUND_COLOR
text-color=$TEXT_COLOR
border-color=$BORDER_COLOR
default-timeout=3000
history=1
max-history=4
max-visible=4
EOF

# Reload Mako to apply the new configuration
makoctl reload

echo "Mako config successfully regenerated and reloaded."
