# Shell variables
# Generated by 'wal'
wallpaper="{wallpaper}"

# Special
background='{background}'
foreground='{foreground}'
cursor='{cursor}'

# Colors
export color0='{color0}'
export color1='{color1}'
export color2='{color2}'
export color3='{color3}'
export color4='{color4}'
export color5='{color5}'
export color6='{color6}'
export color7='{color7}'
export color8='{color8}'
export color9='{color9}'
export color10='{color10}'
export color11='{color11}'
export color12='{color12}'
export color13='{color13}'
export color14='{color14}'
export color15='{color15}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${{LS_COLORS}}:su=30;41:ow=30;42:st=30;44:"
